### ISSUE TITLE
Error Vim 

### ISSUE THREAD

**Issue by terroo** [elvessousa/sobrio#1]
Vim version:
```
$ vim --version
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Jan 23 2023 03:39:31)
Correções incluídas: 1-1157
Modificado por Gentoo-9.0.1157
```

`````
Erro detectado ao processar /home/marcos/.vimrc[44]../home/marcos/.vim/plugged/sobrio/colors/sobrio.vim[139]..function <SNR>30_link:
linha    1:
W18: Caractere inválido no nome do grupo
W18: Caractere inválido no nome do grupo
...

```

**Comment by elvessousa** [comment]
Sorry for the late response. Only now I saw this issue. I'll give it a look.
"Salve rapaziada!"

**Comment by terroo** [comment]
Haha, valeu pelo reconhecimento! \o/

**Comment by elvessousa** [comment]
Eu que agradeço em usar o meu tema! 
Vou dar uma olhada essa semana nesse erro. Mas acredito que seja por conta de um caractere "@" que o Vim não aceita, em uma regra de highlight para o TreeSitter.

**Comment by elvessousa** [comment]
Eu separei os arquivos para o Vim em um tema separado, para evitar conflitos com estes identificadores do TreeSitter. Para usar o tema no Vim, é só alterar o `colorscheme` para `sobrio_vim` em vez de `sobrio` no seu `.vimrc`. Veja se funcionou!
